### ISSUE TITLE
bug：调试断点不正确问题

### ISSUE THREAD

**Issue by npmrun** [FightingDesign/fighting-design#105]
**描述错误**
npm start 后打断点并没有断到正确的位置上

**重现行为的步骤**
1. npm start
2. 添加一个button组件展示
3. 给onClick打上debugger
4. 点击按钮

**预期行为**
源码跳转到对应位置

**屏幕截图**

**版本环境**

我看你使用了`vite-plugin-vue-setup-extend`,所以测试了一下，不推荐使用它，他的问题还没修复呢

**Comment by Tyh2001** [comment]
没太明白你的意，见如下截图：

![button](https://user-images.githubusercontent.com/73180970/180588227-4b5f0391-9c81-4396-be22-f08da68d1724.jpg)
思

**Comment by npmrun** [comment]
如图，你的源码是编译后的，不是你的代码，断点也没有在debugger上

**Comment by Tyh2001** [comment]
默认按钮也是这样的

**Comment by npmrun** [comment]
对啊，所以有问题啊，你可以看它的issue,是有这个问题的，所以可以换`vite-plugin-vue-setup-extend-plus`，有人在它基础上修复了

**Comment by Tyh2001** [comment]
好的 我看下

**Comment by Tyh2001** [comment]
已解决
![3fb6b97141c69786016b2543047f015](https://user-images.githubusercontent.com/73180970/180607178-ef9956f0-e580-4abc-832d-5ed9231bdbcc.jpg)
