### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Awxm** [FightingDesign/fighting-design#178]
建议class部分的层级可以才用bem f-button-default f-button-success 建议为 f-button--success f-button--default

**Comment by Tyh2001** [comment]
> 建议class部分的层级可以才用bem f-button-default f-button-success 建议为 f-button--success f-button--default

可以的，后面加入 class 的规范，封装成函数

**Comment by Givenchy-Coisini** [comment]
这个已经做了么
