### ISSUE TITLE
prop的参数错误

### ISSUE THREAD

**Issue by liulib** [FightingDesign/fighting-design#200]
哥们，props的required参数你写错属性名了，别问我为啥知道的

![image](https://user-images.githubusercontent.com/37172316/195241623-97e32430-5f4e-466d-9760-dcab4454b1ff.png)

![image](https://user-images.githubusercontent.com/37172316/195241736-6a0385d7-3ba5-4065-bbea-69d089434ea6.png)

**Comment by Tyh2001** [comment]
😰😰😰无语，我居然没发现，已修复，下个版本修正
