### ISSUE TITLE
chrome failed to load the dev docs website

### ISSUE THREAD

**Issue by yxw007** [FightingDesign/fighting-design#204]
**Describe the bug**
Chrome failed to load the dev docs website

**To reproduce a behavior**

1. pnpm run dev:docs
2. Errors found, following screenshots

**Expected behavior**
Display the website properly

**Screenshots**
![image](https://user-images.githubusercontent.com/9338717/195380960-6f6991ba-3eb4-4bbb-92d5-e822278b10ef.png)

**Version environment**
- fighting-design: `0.7.0-alpha.4`
- browser: chrome  106.0.5249.103
- win10

**Comment by Tyh2001** [comment]
已解决，详情参考 https://github.com/vuejs/vitepress/issues/1476
