### ISSUE TITLE
功能请求：Dialog 的“关闭按钮”的可点击范围太小

### ISSUE THREAD

**Issue by AkenClub** [FightingDesign/fighting-design#207]
**你在什么场景下产生此需求？**
Dialog 显示后，右上角关闭按钮可点击范围太小了，用户要慢慢移动鼠标到 X 图标上才能关闭。

**你所希望的解决方案？**
增加关闭图标 X 的  padding ?

**描述下你所考虑的备选方案**
描述下你所希望的备选方案。

**其它上下文或截图**
![image](https://user-images.githubusercontent.com/52781316/195494988-83379d4c-7b14-43c3-a898-44604fdcc437.png)

**Comment by Tyh2001** [comment]
好建议，下个版本修复
