### ISSUE TITLE
React支持

### ISSUE THREAD

**Issue by RoyRao2333** [FightingDesign/fighting-design#213]
未来有考虑提供React支持吗？项目真的很棒，期待回复。

**Comment by Tyh2001** [comment]
目前稳定输出的贡献者有点少，可以看下提交，基本上都是我自己在写，很难有时间同时维护两个项目😐😐

**Comment by RoyRao2333** [comment]
> 目前稳定输出的贡献者有点少，可以看下提交，基本上都是我自己在写，很难有时间同时维护两个项目😐😐

好的，还是很感谢开发者付出的心血，star + 观望 ☺️
