### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ccakee** [FightingDesign/fighting-design#309]
![image](https://user-images.githubusercontent.com/63250050/207278645-4e22261c-ae0d-4e31-b066-6f2198a515dc.png)

文档bug  tag大小显示

**Comment by Tyh2001** [comment]
已修复，本周内发布新版本 https://github.com/FightingDesign/fighting-design/commit/e3dfe7e1796cf89481ce540ecf204ea75bc7cca8

**Comment by Tyh2001** [comment]
新版本已修复 (0.11.1)[https://github.com/FightingDesign/fighting-design/releases/tag/0.11.1]

@ccakee
