### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by BBboy01** [FightingDesign/fighting-design#330]
**描述错误**
对 bug 的清晰而简洁的描述。

**重现行为的步骤**

1. 进入[官网](https://fighting.tianyuhao.cn/components/input.html)

**预期行为**
暗黑模式下输入框可以看到 placehoder

**屏幕截图**
![image](https://user-images.githubusercontent.com/59885141/210340108-d62de390-3c9c-43a6-b225-246a44949dcf.png)

**Comment by Tyh2001** [comment]
> **描述错误** 对 bug 的清晰而简洁的描述。
> 
> **重现行为的步骤**
> 
> 1. 进入[官网](https://fighting.tianyuhao.cn/components/input.html)
> 
> **预期行为** 暗黑模式下输入框可以看到 placehoder
> 
> **屏幕截图** ![image](https://user-images.githubusercontent.com/59885141/210340108-d62de390-3c9c-43a6-b225-246a44949dcf.png)

收到~

**Comment by Tyh2001** [comment]
已修复，下个版本更新 https://github.com/FightingDesign/fighting-design/commit/824c6cccc700ca919ebb843a5aec70f7c847ec2e
