### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by long-life233** [FightingDesign/fighting-design#348]
![image](https://user-images.githubusercontent.com/77321887/212605246-401fdff7-50e7-4161-aa28-5df40210fb8d.png)

当传入 button 组件的 slots 改变时，虽然用了 computed 属性，但可能任然不会触发响应式。（因为在计算属性里只有 get 到的属性发生变化，才会导致 computed 回调重新执行。）

建议更改代码为 slots.default && slots.default() && slots.default()[0].children

**Comment by long-life233** [comment]
我还专门写了一篇文章，可以看看，哈哈。https://juejin.cn/post/7189086088567193658

**Comment by long-life233** [comment]
换句话说，因为绑定的是一个引用地址，引用地址没变，所以不会重新触发computed计算函数

**Comment by Tyh2001** [comment]
> 换句话说，因为绑定的是一个引用地址，引用地址没变，所以不会重新触发computed计算函数

哈哈，我正在看这个问题了，我现在发现，解决这个问题都不需要 js 了。直接 css 就可以搞定

**Comment by Tyh2001** [comment]
哦，好像还是需要 js 判断。。。

**Comment by Tyh2001** [comment]
```ts
  const isShowIcon = computed((): boolean => !(slot.default && slot.default() && slot.default()[0].children))
```

这个我尝试了，也同样没有响应式，后来我又使用了 `getCurrentInstance`，也是没有响应式

@long-life233

**Comment by long-life233** [comment]
不会吧。我给你提个pr，你看看。可以看到在 App.vue 里的例子里，如果传入的插槽不为空，那么前后的icon分别会有margin-right：5px、margin-left：5px

**Comment by Tyh2001** [comment]
刚才我测试发现，在行内写插槽判断是直接有响应式的：

```html
:class="[classList, { 'f-button__icon': !$slots.default }]"
```

**Comment by Tyh2001** [comment]
> 不会吧。我给你提个pr，你看看。可以看到在 App.vue 里的例子里，如果传入的插槽不为空，那么前后的icon分别会有margin-right：5px、margin-left：5px

你这样确实是响应式的，但是你可以换一种测试的方式，插槽不绑定响应式的数据，直接写入一段文字，然后手动删除文字，在不刷新页面的情况下，还是没有相应是：

```vue
<f-button type="primary" :before-icon="FIconApps" :after-icon="FIconBluetooth">哈哈哈</f-button>

<f-button type="primary" :before-icon="FIconApps" :after-icon="FIconBluetooth"></f-button>
```

**Comment by long-life233** [comment]
that’s ok, the most important thing is that i had spent time to figure out the problem
