### ISSUE TITLE
使用过程中的若干错误返回

### ISSUE THREAD

**Issue by canyuegongzi** [FightingDesign/fighting-design#375]
1： 类型错误
![image](https://user-images.githubusercontent.com/32031360/228291052-3252f058-9a6a-468a-b83b-664590f604aa.png)

按需引入时类型提示错误，看了源码，导出的类型文件未包含组件的类型，进一步深究发现时 vite 构建使用了 vite-plugin-dts 插件， 插件中的copyDtsFiles配置会复制源码中原有的类型文件，但 ``` packages/fighting-design/_interface``` 目录已经有 index.d.ts文件,  插件运行时会复制覆盖新生成的index.d.ts
![image](https://user-images.githubusercontent.com/32031360/228291815-1d480714-bb4d-4844-b1c7-ce41dc23bd96.png)

建议关闭该选项或者 _interface 下修改index.d.ts

2: 建议入口暴漏_hooks
可能很多场景都需要引入hooks 下的功能
![image](https://user-images.githubusercontent.com/32031360/228293481-b46a03fb-e84a-456b-8f53-f83caf3aaa27.png)

3：文件中独立使用组件库构建时错误
![image](https://user-images.githubusercontent.com/32031360/228295245-6b7cb84f-70be-4f79-9874-bf71fdc8b29c.png)

**Comment by canyuegongzi** [comment]
第三点 vitepress https://github.com/vuejs/vitepress/issues/1399   好像有提及

**Comment by Tyh2001** [comment]
好的 了解

**Comment by Tyh2001** [comment]
最新版本都已经解决
