### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by PassionZale** [FightingDesign/fighting-design#435]
fighting-design/_utils/props/index.ts

这个里面能再提供下组合 `props` 的工具函数吗，例如：

```js
size: [Array, String, Number]
```

**Comment by Tyh2001** [comment]
比如那些组件需要使用？

**Comment by PassionZale** [comment]
和这个 repo 无关，主要是看到了 `_utils/props/index.ts` 里面的一些小函数，感觉很有意思。
之前大部分都是声明一个 `interface`，而后塞到 `defineProps`，没试过 repo 中的这种写法，
看到仓库里面现在只有一种混合类型 `setStringNumberProp`，我想试试别的例如：`setStringArrayProp` 这种，

不知道我这样实现的有没有问题：

```typescript
export const setStringArrayProp = <T = string>(
  defaultValue?: T
): {
  readonly type: PropType<T | string>
  readonly default: () => T | undefined
} => {
  return {
    type: [Array, String] as unknown as PropType<T | string>,
    default: (): T | undefined => defaultValue
  } as const
}
```

看样子是生效了，不知道这么整对不对 😂

<img width="1479" alt="截屏2023-10-29 15 03 13" src="https://github.com/FightingDesign/fighting-design/assets/12482130/78c18256-cfb1-4caa-8395-671ded436a4a">

**Comment by Tyh2001** [comment]
这应该是 ` type: [Array, String] as unknown as PropType<T | T[]>` 吧？
